name: Sync jobs folder to TESTE-B

on:
  push:
    branches: 
      - main
    paths:
      - 'collections/jobs/**'

jobs:
  sync_jobs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout TESTE-A repository
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Clone TESTE-B repository
      run: |
        # [Passo 1] - Clonar o repositório B
        git clone https://x-access-token:${{ secrets.REPO_B }}@github.com/manoel-esx/TEST-B.git repo-b
    - name: Sync jobs folder from TESTE-A to TESTE-B
      run: |
        # [Passo 2] - Cria a pasta caso precisar
        mkdir -p repo-b/collections/jobs
        
        # [Passo 3] - Copia os arquivos para o repositório B
        rsync -av --delete collections/jobs/ repo-b/collections/jobs/
        
        # [Passo 3] - Configuração do Git
        cd repo-b
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        
        # [Passo 4] - Guardar mudanças se houver e sincronizar
        if git diff --quiet; then
          echo "No local changes to stash"
        else
          git stash
          STASH_APPLIED=true
        fi
        git pull --rebase origin main
        
        # [Passo 5] - Restaurar mudanças se necessário
        if [ "${STASH_APPLIED}" = true ]; then
          git stash pop
        fi
    
        # [Passo 6] - Commit e push das alterações
        git add collections/jobs/*
        git commit -m "Sync jobs folder from TESTE-A" || echo "Nenhuma mudança para commitar"
        git push origin main