name: Sync jobs folder to Azure DevOps

on:
  push:
    paths:
      - 'jobs/**'

jobs:
  sync_jobs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout TESTE-A repository
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Sync jobs folder to Azure DevOps
      run: |
        # Clone the Azure DevOps repository
        git clone https://${{ secrets.AZURE_PAT }}:@dev.azure.com/esx/Portal%20ESX%20Premium/_git/teste-apagar repo-azure
        
        # Copy files to the Azure DevOps repo
        rsync -av --delete jobs/ repo-azure/jobs/
        
        # Configure Git for Azure DevOps
        cd repo-azure
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        
        # Commit and push changes
        git add jobs/*
        git commit -m "Sync jobs folder to Azure DevOps"
        git push origin main
