name: Sync jobs folder to TESTE-B

on:
  push:
    branches: 
      - main
    paths:
      - 'collections/jobs/**'

jobs:
  sync_jobs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout TESTE-A repository
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Passo 1 - Clonar o repositório B
      run: |
        git clone https://x-access-token:${{ secrets.REPO_B_PAT }}@github.com/manoel-esx/TEST-B.git repo-b

    - name: Passo 2 - Cria a pasta caso precisar
      run: |
        mkdir -p repo-b/collections/jobs
        
    - name: Passo 3 - Copia os arquivos para o repositório B
      run: |
        rsync -av --delete collections/jobs/ repo-b/collections/jobs/
        
    - name: Passo 4 - Configuração do Git
      run: |
        cd repo-b
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        
    - name: Passo 5 - Guardar mudanças se houver e sincronizar
      run: |
        if git diff --quiet; then
          echo "No local changes to stash"
        else
          git stash
          STASH_APPLIED=true
        fi
        git pull --rebase origin main
        
    - name: Passo 6 - Restaurar mudanças se necessário
      run: |
        if [ "${STASH_APPLIED}" = true ]; then
          git stash pop
        fi
    
    - name: Passo 7 - Commit e push das alterações
      run: |
        git add -A collections/jobs/*
        git commit -m "Sync jobs folder from TESTE-A" || echo "Nenhuma mudança para commitar"
        git push origin main
