name: Sync jobs folder to TESTE-B

on:
  push:
    branches: 
      - main
    paths:
      - 'collections/jobs/**'

jobs:
  sync_jobs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout TESTE-A repository
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Passo 1 - Clonar o repositório B
      run: |
        git clone https://x-access-token:${{ secrets.REPO_B_PAT }}@github.com/manoel-esx/TEST-B.git repo-b

    - name: Passo 2 - Excluir a pasta collections/jobs no repositório B
      run: |
        rm -rf repo-b/collections/jobs
        mkdir -p repo-b/collections/jobs

    - name: Passo 3 - Copiar os arquivos atualizados do repositório A para o repositório B
      run: |
        rsync -av collections/jobs/ repo-b/collections/jobs/

    - name: Passo 4 - Configurar o Git para push
      run: |
        cd repo-b
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Passo 5 - Commit e push das alterações
      run: |
        cd repo-b
        git add .
        git commit -m "Sync entire jobs folder from TESTE-A" || echo "Nenhuma mudança para commitar"
        git push https://x-access-token:${{ secrets.REPO_B_PAT }}@github.com/manoel-esx/TEST-B.git main
